version: '3.9'

services:
  docker_base:
    build:
      context: services/docker_base
    image: docker_base

  jupyter:
    build:
      context: services/jupyter
      args:
        base_image: docker_base
        python_path: "/app"
    ports:
      - 1234:1234
    volumes:
      - ./notebooks:/app/notebooks
      - ./lib:/app/pylib/lib
    environment:
      - PYTHONPATH=/app/pylib:$PYTHONPATH
